<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Language;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = [
            'Afrikaans', 
            'Albanian', 
            'Amharic', 
            'Arabic', 
            'Aramaic', 
            'Armenian', 
            'Austro-Bavarian German', 
            'Aymara', 
            'Azerbaijani', 
            'Belarusian', 
            'Belizean Creole', 
            'Bengali', 
            'Berber', 
            'Bislama', 
            'Bosnian', 
            'Bulgarian', 
            'Burmese', 
            'Carolinian', 
            'Catalan', 
            'Chamorro', 
            'Chewa', 
            'Chibarwe', 
            'Chinese', 
            'Comorian', 
            'Cook Islands Māori', 
            'Croatian', 
            'Czech', 
            'Danish', 
            'Dari', 
            'Dutch', 
            'Dzongkha', 
            'English', 
            'Estonian', 
            'Faroese', 
            'Fiji Hindi', 
            'Fijian', 
            'Filipino', 
            'Finnish', 
            'French', 
            'Georgian', 
            'German', 
            'Gilbertese', 
            'Greek', 
            'Greenlandic', 
            'Guaraní', 
            'Guernésiais', 
            'Haitian Creole', 
            'Hassaniya', 
            'Hebrew', 
            'Herero', 
            'Hindi', 
            'Hiri Motu', 
            'Hungarian', 
            'Icelandic', 
            'Indonesian', 
            'Irish', 
            'Italian', 
            'Jamaican Patois', 
            'Japanese', 
            'Jèrriais', 
            'Kalanga', 
            'Kazakh', 
            'Khmer', 
            'Khoekhoe', 
            'Khoisan', 
            'Kikongo', 
            'Kinyarwanda', 
            'Kirundi', 
            'Korean', 
            'Kwangali', 
            'Kyrgyz', 
            'Lao', 
            'Latin', 
            'Latvian', 
            'Lingala', 
            'Lithuanian', 
            'Lozi',
            'Luxembourgish', 
            'Macedonian', 
            'Malagasy', 
            'Malay', 
            'Maldivian', 
            'Maltese', 
            'Manx', 
            'Marshallese', 
            'Mauritian Creole', 
            'Moldavian', 
            'Mongolian', 
            'Montenegrin', 
            'Māori', 
            'Nauru', 
            'Ndau', 
            'Ndonga', 
            'Nepali', 
            'New Zealand Sign Language', 
            'Niuean', 
            'Norfuk', 
            'Northern Ndebele', 
            'Northern Sotho', 
            'Norwegian', 
            'Norwegian Bokmål', 
            'Norwegian Nynorsk', 
            'Palauan', 
            'Papiamento', 
            'Pashto', 
            'Persian (Farsi)', 
            'Polish', 
            'Portuguese', 
            'Quechua', 
            'Romani',
            'Romanian', 
            'Romansh', 
            'Russian', 
            'Sami', 
            'Samoan', 
            'Sango', 
            'Serbian', 
            'Seychellois Creole', 
            'Shona', 
            'Sinhala', 
            'Slovak', 
            'Slovene', 
            'Somali', 
            'Sorani', 
            'Sotho', 
            'Southern Ndebele', 
            'Southern Sotho', 
            'Spanish', 
            'Swahili', 
            'Swazi', 
            'Swedish', 
            'Swiss German', 
            'Tajik', 
            'Tamil', 
            'Tetum', 
            'Thai', 
            'Tigrinya', 
            'Tok Pisin', 
            'Tokelauan', 
            'Tonga', 
            'Tongan', 
            'Tshiluba', 
            'Tsonga', 
            'Tswana', 
            'Turkish', 
            'Turkmen', 
            'Tuvaluan', 
            'Ukrainian', 
            'Upper Guinea Creole', 
            'Urdu', 
            'Uzbek', 
            'Venda', 
            'Vietnamese', 
            'Xhosa', 
            'Zimbabwean Sign Language'
        ];

        foreach($languages as $language) {
            $new_language = new Language;
            $new_language->name = $language;
            $new_language->save();
        }
    }
}
